services:
  mc:
    image: itzg/minecraft-server:java17
    pull_policy: daily
    labels:
      # Set lazymc.enabled to true to enable lazymc on this container
      - lazymc.enabled=true
      # Required to find the container to manage it
      - lazymc.group=mc
      # Point to the service name of the Minecraft server
      - lazymc.server.address=mc:25565
      # The minecraft client version of the forge server
      - lazymc.public.version=1.20.1
      # The minecraft protocol version of the forge server
      - lazymc.public.protocol=763
      # Set to true on a forge server
      - lazymc.join.hold.timeout=29
      - lazymc.server.wake_whitelist
      - lazymc.server.forge=true
      - lazymc.time.sleep.after=60
      - lazymc.time.minimum_online_time=300
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      VERSION: "1.20.1"
      TYPE: FORGE
      FORGE_VERSION: "47.4.13"
      EULA: "true"
      MEMORY: "8G"
      # USE_AIKAR_FLAGS: "TRUE"
      USE_MEOWICE_FLAGS: "true"
      GUI: "FALSE"
      OVERRIDE_SERVER_PROPERTIES: "true"
      OVVERIDE_WHITELIST: "true"
      WHITELIST: |
        pieceofpaypur
        bmo_btw
      OVERRIDE_OPS: "true"
      OPS: |
        pieceofpaypur
      LEVEL:
        b1mo
      DIFFICULTY: "normal"
      SPAWN_PROTECTION: "0"
      MAX_TICK_TIME: "-1"
      ALLOW_FLIGHT: "true"
      VIEW_DISTANCE: "20"
      SNOOPER_ENABLED: "false"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data:Z
      - ./b1mo:/data/b1mo
      - ./mods:/mods
      - ./config:/config
      - ./kubejs:/data/kubejs
    restart: unless-stopped

  lazymc:
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    restart: unless-stopped
    volumes:
      # you should mount the minecraft server dir under /server, using read only.
      - data:/server:ro
      # you need to supply the docker socket, so that the container can run docker command
      - /run/user/1000/docker.sock:/var/run/docker.sock:rw
    ports:
      # lazymc-docker-proxy acts as a proxy, so there is
      # no need to expose the server port on the Minecraft container
      - "25565:25565"

volumes:
  data:
